//! The digest must be the origin's, byte for byte.
//!
//! `ScryNotary` commits a depot's digest on chain, and **two implementations of
//! a number that becomes money is what `CLAUDE.md` invariant 3 forbids.** There
//! are two: this one, which the client computes, and `meter/depot_doc.py`,
//! which the origin serves. A disagreement between them is a player being told
//! the wrong thing about a build they are about to run.
//!
//! This file is the whole justification for that pair existing. The vectors are
//! frozen golden values — they were generated by the original implementation
//! and both sides now match them.
//!
//! ⚠ **The vectors are no longer regenerable and that is on purpose.** Their
//! generator lived in the desktop client that was deleted on 2026-08-07, and
//! nothing replaced it: a golden file you can rewrite from one side is a golden
//! file that side can silently redefine. If a legitimate format change is ever
//! needed, add vectors — never edit these, and never "regenerate" them from
//! whichever implementation happens to be in front of you.
//!
//! ⚠ If this test is ever deleted, weakened, or allowed to skip, one of the two
//! implementations becomes the bug the invariant is about.

use scry_depot::{canonical, digest};
use serde_json::Value;

const VECTORS: &str = include_str!("digest_vectors.json");

#[test]
fn canonical_bytes_match_python() {
    let cases: Vec<Value> = serde_json::from_str(VECTORS).expect("vectors parse");
    assert!(cases.len() >= 16, "vectors got smaller — regenerate, do not trim");
    for case in &cases {
        let name = case["name"].as_str().unwrap();
        let want = case["canonical_utf8"].as_str().unwrap();
        let got = canonical(&case["depot"]).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(
            String::from_utf8(got).unwrap(),
            want,
            "{name}: canonical JSON diverged from Python's"
        );
    }
}

#[test]
fn digests_match_python() {
    let cases: Vec<Value> = serde_json::from_str(VECTORS).expect("vectors parse");
    for case in &cases {
        let name = case["name"].as_str().unwrap();
        let want = case["digest"].as_str().unwrap();
        let got = digest(&case["depot"]).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(got, want, "{name}: digest diverged from Python's");
    }
}

#[test]
fn notary_and_signature_are_excluded() {
    // They are written *about* the digest, so including them would make the
    // value unfixable. A depot carrying only a notary hashes as an empty one.
    let bare = serde_json::json!({});
    let noted = serde_json::json!({"notary": {"tx": "0xdead"}, "signature": "0xbeef"});
    assert_eq!(digest(&bare).unwrap(), digest(&noted).unwrap());
}

#[test]
fn a_float_is_refused_rather_than_hashed() {
    // Python and Rust agree on 1.0 and disagree on 1e+100 vs 1e100. A depot
    // has no float field, so refusing is the failure that gets noticed and
    // hashing is the one that silently disagrees with the chain.
    let err = digest(&serde_json::json!({"bytes": 1.5})).unwrap_err();
    assert!(err.0.contains("float"), "{}", err.0);
    assert!(err.0.contains("bytes"), "should name the field: {}", err.0);
}

#[test]
fn key_order_in_the_input_cannot_change_the_output() {
    let a: Value = serde_json::from_str(r#"{"a":1,"b":2,"c":3}"#).unwrap();
    let b: Value = serde_json::from_str(r#"{"c":3,"b":2,"a":1}"#).unwrap();
    assert_eq!(digest(&a).unwrap(), digest(&b).unwrap());
}
