//! What the controls in [`crate::windows`] actually do.
//!
//! # Why this is its own module
//!
//! `windows.rs` draws and decides nothing — that rule is what keeps it
//! constructible with no disk, no origin and no display. The behaviour has to
//! live somewhere, and putting it in the binary would have made it the one part
//! of this client with no test at all: an integration test cannot reach into a
//! `[[bin]]`.
//!
//! So it lives here, in the library, and the binary is left as composition.
//!
//! # Asking is injected, and that is the whole reason this is testable
//!
//! A modal password dialog cannot be driven by a test — it blocks on a human.
//! [`Ask`] is therefore a parameter, the same injection the origin's own
//! suites use when they pass `opener=` rather than opening a real browser. In
//! the client it is [`real_ask`]; in `examples/click.rs` it is a script, which
//! lets the REAL button callback run end to end with no hands.
//!
//! [`ask_consent`] is the same shape one layer up: the *decision* is injected
//! into [`crate::consent::Doorbell::pump`], so the queue, the refusals and the
//! thread crossing are unit-tested with no display at all, and only the window
//! itself needs one.
//!
//! ⚠ **A cancelled dialog is not an empty passphrase.** `Ask` returns
//! `Option`, and every caller treats `None` as *the player changed their mind*
//! and returns without touching the keystore. Collapsing those two would make
//! pressing Escape write a key encrypted under the empty string.

use crate::theme;
use crate::windows::{AccountWindow, SigningWindow};
use fltk::{app, dialog, prelude::*};
use scry_broker::signer::Signer;
use std::cell::RefCell;
use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::sync::{Arc, Mutex};

/// The one account, shared by everything that touches it.
///
/// ⚠ **`Arc<Mutex<…>>` and not `Rc<RefCell<…>>`, because the game door is on
/// another thread.** The windows all run on FLTK's thread and `Rc` was right
/// while they were the only readers — then `prove` arrived, and a game asking
/// the launcher to prove an identity is served from the door's thread. An
/// unlocked account has to be visible there or `prove` can only ever answer
/// "locked", which would be a launcher that unlocks in a window nothing else
/// can see.
pub type Shared = Arc<Mutex<scry_vault::LocalSigner>>;

/// How the wiring asks for a secret. `None` means the player cancelled.
pub type Ask = Rc<dyn Fn(&str) -> Option<String>>;

/// How it reports back — a message, and an alert for a refusal.
pub type Tell = Rc<dyn Fn(Told, &str)>;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Told {
    Done,
    Refused,
}

/// The real dialogs. Masked, because two of the three things asked for here are
/// secrets and the third is a private key.
pub fn real_ask() -> Ask {
    Rc::new(|prompt| dialog::password_default(prompt, ""))
}

pub fn real_tell() -> Tell {
    Rc::new(|kind, text| match kind {
        Told::Done => dialog::message_default(text),
        Told::Refused => dialog::alert_default(text),
    })
}

/// Make and import — the whole of "how do I get an account".
///
/// **Nothing here touches the network.** The key is generated by the OS pool,
/// encrypted, and written, all on this machine (`CLAUDE.md` invariant 7).
pub fn wire_account(
    account_w: &AccountWindow,
    signing_w: &SigningWindow,
    signer: &Shared,
    keystore: &Path,
    ask: Ask,
    tell: Tell,
) {
    if let Some(b) = account_w.make.clone() {
        let mut b = b;
        let (signer, aw, sw, ks) = (
            Arc::clone(signer),
            account_w.clone(),
            signing_w.clone(),
            keystore.to_path_buf(),
        );
        let (ask, tell) = (Rc::clone(&ask), Rc::clone(&tell));
        b.set_callback(move |_| {
            let Some(pass) = ask_twice(&ask, &tell, "A passphrase for the new account:") else {
                return;
            };
            match scry_vault::LocalSigner::create(&ks, &pass) {
                Ok(s) => adopt(&signer, &aw, &sw, &ks, s, &tell),
                Err(e) => tell(Told::Refused, &e),
            }
        });
    }

    if let Some(b) = account_w.import.clone() {
        let mut b = b;
        let (signer, aw, sw, ks) = (
            Arc::clone(signer),
            account_w.clone(),
            signing_w.clone(),
            keystore.to_path_buf(),
        );
        let (ask, tell) = (Rc::clone(&ask), Rc::clone(&tell));
        b.set_callback(move |_| {
            // Masked like a passphrase: this input IS a private key, and it is
            // the one field in this program that must never be painted.
            let Some(raw) = ask("The private key to adopt (64 hex characters):") else {
                return;
            };
            let secret = match parse_secret(&raw) {
                Ok(s) => s,
                Err(e) => return tell(Told::Refused, &e),
            };
            let Some(pass) = ask_twice(&ask, &tell, "A passphrase to encrypt it with:") else {
                return;
            };
            match scry_vault::LocalSigner::import(&ks, &pass, &secret) {
                Ok(s) => adopt(&signer, &aw, &sw, &ks, s, &tell),
                Err(e) => tell(Told::Refused, &e),
            }
        });
    }
}

/// Unlock and its inverse — the two acts that decide whether a key is in
/// memory, and the only ones Signing offers.
pub fn wire_signing(
    signing_w: &SigningWindow,
    signer: &Shared,
    ask: Ask,
    tell: Tell,
) {
    // Lock first, because it must work even if unlock's wiring ever grows a
    // way to fail: forgetting the key is the button that may not be dead.
    // No dialog and no confirmation — locking costs a passphrase to undo,
    // which is exactly the cost it is supposed to impose.
    if let Some(b) = signing_w.lock.clone() {
        let mut b = b;
        let signer = Arc::clone(signer);
        let mut status = signing_w.status.clone();
        b.set_callback(move |_| {
            if let Ok(mut s) = signer.lock() {
                s.lock();
                status.set_label(&s.status());
                app::redraw();
            }
        });
    }

    let Some(b) = signing_w.unlock.clone() else {
        return;
    };
    let mut b = b;
    let signer = Arc::clone(signer);
    let mut status = signing_w.status.clone();
    b.set_callback(move |_| {
        let Some(pass) = ask("Passphrase:") else {
            return;
        };
        let mut s = signer.lock().expect("signer lock");
        match s.unlock(&pass) {
            Ok(()) => {
                status.set_label(&s.status());
                app::redraw();
                tell(
                    Told::Done,
                    "Unlocked for this session.\n\nIt is forgotten when this program closes.",
                );
            }
            // The vault draws the line between a wrong passphrase and a corrupt
            // file. Do not blur it back by rewording the message here.
            Err(e) => tell(Told::Refused, &e),
        }
    });
}

/// How often the main thread looks for a game waiting at the door.
///
/// A poll rather than `app::awake`, and the reason is soundness: waking FLTK
/// from the door thread means handing it a closure built over there, and the
/// closure this one needs opens windows. 150ms is under what anyone perceives
/// as lag on a prompt a human is about to read, and an idle launcher spends
/// nothing measurable on it.
const DOORBELL_POLL: f64 = 0.15;

/// Show the real consent prompt and wait for the player.
///
/// **Runs a nested event loop**, which is what every modal in this toolkit
/// does — `dialog::password_default` above is the same shape. The door thread
/// is parked on the answer this returns, so the loop ends only when a button
/// is pressed or the window goes away.
///
/// ⚠ **Every exit that is not a button is a refusal.** The window manager's
/// close, the app quitting out from under the prompt, a main loop that stops
/// dispatching — all of them leave `answer` untouched at `None`. That
/// direction is not arbitrary: a wrong refusal costs a click, and a wrong
/// grant costs a signature the player never approved.
pub fn ask_consent(signer: &Shared, ask: &crate::consent::Ask) -> Option<u32> {
    // Read the account state BEFORE the window exists, and drop the lock
    // before the nested loop starts. Holding it across the prompt would freeze
    // the Signing window's Unlock button for exactly as long as the prompt is
    // up — which is the one moment a player is most likely to press it.
    let (address, unlocked) = match signer.lock() {
        Ok(s) => (s.address(), s.is_unlocked()),
        Err(_) => (None, false),
    };

    let mut win = crate::windows::consent(ask, address.as_deref(), unlocked);
    let answer = wire_consent(&win);

    win.window.show();
    while win.window.shown() {
        // `wait` returning false is the app shutting down. Breaking here is
        // what stops a closing launcher from parking the door thread forever
        // on a window that will never be answered.
        if !app::wait() {
            break;
        }
    }
    win.window.hide();
    answer.get()
}

/// Give a consent window's buttons their meaning, and hand back the cell they
/// write into.
///
/// Split out of [`ask_consent`] so `examples/click.rs` can press the **real**
/// buttons: a nested event loop is the one part of a modal a test cannot
/// drive, so it is the only part left outside this function. Everything that
/// decides what a press means is in here, where a test can reach it.
pub fn wire_consent(win: &crate::windows::ConsentWindow) -> Rc<std::cell::Cell<Option<u32>>> {
    let answer = Rc::new(std::cell::Cell::new(None::<u32>));

    for (i, b) in win.allow.iter().enumerate() {
        // Paired by index with the table the window drew from, rather than by
        // reading the label back off the button. A grant is a number and the
        // label is decoration; recovering one from the other would put "how
        // many signatures" behind a string comparison.
        let Some((_, grant)) = crate::consent::ALLOWANCES.get(i).copied() else {
            continue;
        };
        let (mut b, answer, mut w) = (b.clone(), Rc::clone(&answer), win.window.clone());
        b.set_callback(move |_| {
            answer.set(Some(grant));
            w.hide();
        });
    }

    let (refused, mut w) = (Rc::clone(&answer), win.window.clone());
    let mut refuse = win.refuse.clone();
    refuse.set_callback(move |_| {
        // Deliberately writes no value: `None` is already what the cell holds,
        // and Refuse only ends the wait. Anything else here would mean the
        // refusal path had a value that could be got wrong.
        refused.set(None);
        w.hide();
    });

    answer
}

/// Answer the door for as long as the launcher is open.
///
/// Registers a repeating timeout on FLTK's thread — the one thread allowed to
/// open a window — and drains [`crate::consent::Doorbell`] on each tick.
///
/// ⚠ **The re-entrancy guard is defensive, and the ordering below is what
/// actually holds today.** `ask_consent` runs a nested event loop and FLTK
/// dispatches timeouts inside one — but this timeout is not re-armed until
/// `pump` returns, so it cannot fire while a prompt is up. The flag exists
/// because that safety is a property of *where* `repeat_timeout3` sits, and
/// moving it to the top of the callback is the most natural refactor in the
/// world. Without the flag, that edit silently starts stacking a second game's
/// prompt over the one the player is reading — in the one window where their
/// answer authorises something.
pub fn serve_consent(bell: crate::consent::Doorbell, signer: Shared) {
    let busy = Rc::new(std::cell::Cell::new(false));
    app::add_timeout3(DOORBELL_POLL, move |handle| {
        if !busy.get() {
            busy.set(true);
            bell.pump(&mut |ask| ask_consent(&signer, ask));
            busy.set(false);
        }
        app::repeat_timeout3(DOORBELL_POLL, handle);
    });
}

/// The two origin calls the website pairing makes, injectable so the flow is
/// testable with no network — the same seam [`Ask`] is for dialogs.
pub trait SigninHttp {
    /// `GET {host}/api/signin/{code}/challenge` — is this code real and waiting?
    fn challenge(&self, host: &str, code: &str) -> scry_net::Fetched<serde_json::Value>;
    /// `POST {host}/api/signin/{code}/proof` — deliver the signed message.
    fn deliver(&self, host: &str, code: &str, body: &serde_json::Value)
        -> scry_net::Fetched<serde_json::Value>;
}

pub struct RealSigninHttp;

impl SigninHttp for RealSigninHttp {
    fn challenge(&self, host: &str, code: &str) -> scry_net::Fetched<serde_json::Value> {
        scry_net::Net::new().get_json(&format!("{host}/api/signin/{code}/challenge"))
    }
    fn deliver(&self, host: &str, code: &str, body: &serde_json::Value)
        -> scry_net::Fetched<serde_json::Value> {
        scry_net::Net::new().post_json_told(&format!("{host}/api/signin/{code}/proof"), body)
    }
}

/// Pair a browser with this account — the GUI half of `scry signin`
/// (`docs/client/SIGN-IN.md`; the origin is `meter/signin.py`).
///
/// Returns the sentence to show the player, or the refusal.
///
/// Two properties are the point, and both are for the machine someone else
/// can sit down at:
///
/// * **The passphrase is asked EVERY time, unlocked or not.** A pairing signs
///   a browser in *as this account*, so it is an act of the
///   passphrase-holder — an already-unlocked launcher must not let whoever is
///   at the keyboard pair their own browser. `unlock` re-derives from the
///   file, so answering it IS proving the passphrase.
/// * **A transient unlock stays transient.** If the account was locked before
///   the pairing, it is locked again after — signing a browser in leaves no
///   live signer behind.
///
/// What the GUI pairing deliberately does not do: watch the relay. Approving
/// a page's signature requests is a stream of prompts, and the CLI
/// (`scry signin`, attached in a terminal) is the surface built for that. A
/// code works once, so the watch wants its own code, typed there.
pub fn pair_browser(
    signer: &Shared,
    host: &str,
    raw_code: &str,
    ask: &Ask,
    http: &dyn SigninHttp,
) -> Result<String, String> {
    let code: String = raw_code
        .trim()
        .to_uppercase()
        .chars()
        .filter(|c| *c != '-')
        .collect();
    scry_broker::protocol::check_nonce(&code).map_err(|r| {
        format!(
            "That is not a sign-in code — {}. The page shows one like ABCD-2345.",
            r.reason
        )
    })?;

    let (exists, address, was_unlocked) = {
        let s = signer.lock().map_err(|_| "the signer is busy".to_string())?;
        (s.exists(), s.address(), s.is_unlocked())
    };
    if !exists {
        return Err(
            "No account on this machine — make one first. The pairing is this \
             account proving itself to a browser, so there is nothing to pair yet."
                .into(),
        );
    }
    let address = address.ok_or_else(|| "the keystore names no address".to_string())?;

    // Look before the passphrase: a typo costs one request, never a dialog.
    let asked = http.challenge(host, &code);
    if asked.value.is_none() {
        return Err(match asked.status {
            Some(404) => format!(
                "{code} is not waiting to sign in — it expired or was mistyped. \
                 The browser page shows a fresh one."
            ),
            Some(409) => "That code was already used — a sign-in code works once.".into(),
            _ if !asked.reachable => format!("could not reach {host} — {}", asked.why),
            _ => format!("the origin refused the code — {}", asked.why),
        });
    }

    let domain = host
        .split_once("://")
        .map(|(_, rest)| rest)
        .unwrap_or(host)
        .trim_end_matches('/')
        .to_string();
    let message = scry_broker::protocol::signin_message(
        &domain,
        &address,
        &code,
        &scry_broker::protocol::now_iso8601(),
    );

    // The full message rides in the prompt: the player reads what is signed
    // in the same dialog that asks for the passphrase to sign it.
    let prompt =
        format!("About to sign exactly this, and nothing else:\n\n{message}\n\nPassphrase:");
    let Some(pass) = ask(&prompt) else {
        return Err("Cancelled — nothing was signed.".into());
    };

    let out = {
        let mut s = signer.lock().map_err(|_| "the signer is busy".to_string())?;
        s.unlock(&pass)?;
        let signed = s.sign(&message, "sign the website in").map_err(|r| r.reason);
        if !was_unlocked {
            s.lock();
        }
        signed?
    };
    let sig = out
        .get("signature")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("")
        .to_string();
    if sig.is_empty() {
        return Err("the signer returned no signature".into());
    }

    let resp = http.deliver(
        host,
        &code,
        &serde_json::json!({ "message": message, "signature": sig }),
    );
    let Some(v) = resp.value else {
        return Err(format!("could not deliver the proof — {}", resp.why));
    };
    if v.get("ok").and_then(serde_json::Value::as_bool) != Some(true) {
        return Err(format!(
            "the origin refused the proof — {}",
            v.get("error")
                .and_then(serde_json::Value::as_str)
                .unwrap_or(&resp.why)
        ));
    }
    Ok(format!(
        "Signed in — the browser showing {code} now reads as\n{address}\n\n\
         No session was created anywhere: the page holds a proof, and every act\n\
         still asks for its own signature. To also approve that page's signature\n\
         requests, pair a fresh code from a terminal: scry signin <code>"
    ))
}

/// Give the Account window's pairing row its meaning.
///
/// ⚠ The two origin calls run on the UI thread and block it — the same trade
/// the binary's startup reads make, and short on a healthy origin. If it ever
/// grows past two calls it wants the doorbell's thread shape instead.
pub fn wire_signin(
    account_w: &AccountWindow,
    signer: &Shared,
    host: &str,
    ask: Ask,
    tell: Tell,
    http: Rc<dyn SigninHttp>,
) {
    let (Some(b), Some(code_in)) = (account_w.signin.clone(), account_w.signin_code.clone())
    else {
        return;
    };
    let mut b = b;
    let signer = Arc::clone(signer);
    let host = host.to_string();
    b.set_callback(move |_| {
        let raw = code_in.value();
        match pair_browser(&signer, &host, &raw, &ask, http.as_ref()) {
            Ok(msg) => {
                let mut ci = code_in.clone();
                ci.set_value("");
                tell(Told::Done, &msg);
            }
            Err(e) => tell(Told::Refused, &e),
        }
    });
}

/// The published client version NEWER than `mine`, off the origin's
/// `/api/launcher` card — or `None`, which deliberately covers four different
/// states: current, ahead (a dev build is not nagged), no client published,
/// and a card we could not read. The caller must therefore never render
/// `None` as "up to date" — the corner stays a bare local version, which
/// claims nothing about currency. Same three-answer discipline as `scry
/// check`, whose comment also carries the ruling this UI half inherits: **a
/// notice, never a self-update** — a binary that replaces itself must be
/// trusted absolutely, and the package manager or the download page does the
/// swap in the open.
pub fn newer_client(card: Option<&serde_json::Value>, mine: &str) -> Option<String> {
    let there = card?.get("client")?.get("version")?.as_str()?;
    (scry_depot::update::version_cmp(there, mine) == std::cmp::Ordering::Greater)
        .then(|| there.to_string())
}

/// How often the idle relock looks at the clock. Coarse on purpose: the
/// threshold is minutes, and a check that ran hot would be spending wakeups
/// to gain seconds of precision on a lock nobody is racing.
const RELOCK_POLL: f64 = 30.0;

/// Relock the unlocked key after it sits idle.
///
/// "Unlocked for this session" was the whole story, and for a machine that is
/// only ever the player's own it is a fine one — but a launcher left open on a
/// shared desk holds a live signer for anyone who sits down next. This is the
/// bounded version: every signature refreshes the account's `last_used`, so an
/// afternoon of play never relocks mid-session, and an unlock nobody has used
/// since lunch stops being one.
///
/// `after` of zero disables it — that is the operator's own machine saying so
/// (`SCRY_RELOCK_MINUTES=0`), not a default.
///
/// What this is NOT: a security boundary against a process running as you.
/// `local.rs` says it first — the process that draws the window holds the key,
/// and rung 2's answer is the arca, not a timer. This narrows the WINDOW a
/// walk-by has, which is real, and nothing more.
pub fn serve_relock(signer: Shared, signing_w: &SigningWindow, after: std::time::Duration) {
    if after.is_zero() {
        return;
    }
    let mut status = signing_w.status.clone();
    app::add_timeout3(RELOCK_POLL, move |handle| {
        if let Ok(mut s) = signer.lock() {
            if s.idle().is_some_and(|idle| idle >= after) {
                s.lock();
                status.set_label(&s.status());
                app::redraw();
            }
        }
        app::repeat_timeout3(RELOCK_POLL, handle);
    });
}

fn ask_twice(ask: &Ask, tell: &Tell, prompt: &str) -> Option<String> {
    let first = ask(prompt)?;
    let again = ask("Type it again:")?;
    if first != again {
        tell(Told::Refused, "Those two did not match — nothing was written.");
        return None;
    }
    Some(first)
}

/// Take a freshly made account as this launcher's, and say so on screen.
///
/// Updates in place rather than rebuilding: a rebuilt window loses where the
/// player put it and reads as a flicker.
fn adopt(
    signer: &Shared,
    account_w: &AccountWindow,
    signing_w: &SigningWindow,
    keystore: &Path,
    new_signer: scry_vault::LocalSigner,
    tell: &Tell,
) {
    let address = new_signer.address().unwrap_or_default();
    let status = new_signer.status();
    *signer.lock().expect("signer lock") = new_signer;

    let mut addr = account_w.address.clone();
    let mut note = account_w.note.clone();
    addr.set_label(&address);
    addr.set_label_color(theme::INK);
    note.set_label("made on this machine, and transmitted nowhere");
    // Both doors close: this window never offers to replace a key, and the
    // vault would refuse anyway. Deactivating says why before it is pressed.
    for b in [account_w.make.clone(), account_w.import.clone()].into_iter().flatten() {
        let mut b = b;
        b.deactivate();
    }
    let mut st = signing_w.status.clone();
    st.set_label(&status);
    app::redraw();

    tell(
        Told::Done,
        &format!(
            "Account created.\n\n{address}\n\nThe keystore is the only copy of this key:\n{}\n\n\
             Back it up. The passphrase cannot be reset — nobody else has it, including scry.\n\n\
             Restart the launcher to unlock it in Signing.",
            keystore.display()
        ),
    );
}

/// 32 bytes from hex.
///
/// ⚠ **No input ever reaches the error.** The input is a private key, and a
/// message that echoed a mistyped one would carry it into a screenshot, a
/// terminal scrollback or a bug report. Say the shape, never the value.
pub fn parse_secret(raw: &str) -> Result<[u8; 32], String> {
    let hex = raw.trim();
    let hex = hex.strip_prefix("0x").or_else(|| hex.strip_prefix("0X")).unwrap_or(hex);
    if hex.len() != 64 {
        return Err(format!(
            "A private key is 64 hex characters (32 bytes); that was {}.",
            hex.len()
        ));
    }
    let mut out = [0u8; 32];
    for (i, b) in out.iter_mut().enumerate() {
        *b = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16)
            .map_err(|_| "That is not hexadecimal — nothing was written.".to_string())?;
    }
    Ok(out)
}

/// A scripted [`Ask`] — hands back the given answers in order, then `None`.
///
/// Lives beside the thing it doubles rather than in a test file, because
/// `examples/click.rs` uses it too and a second copy would drift.
pub fn scripted_ask(answers: Vec<Option<String>>) -> Ask {
    let queue = RefCell::new(answers.into_iter());
    Rc::new(move |_prompt| queue.borrow_mut().next().unwrap_or(None))
}

/// Somewhere for a test to read what the player was told.
pub fn recording_tell(log: Rc<RefCell<Vec<(Told, String)>>>) -> Tell {
    Rc::new(move |kind, text| log.borrow_mut().push((kind, text.to_string())))
}

/// Where the keystore lives, for a caller that wants to show it.
pub fn keystore_path() -> PathBuf {
    scry_vault::keystore_path()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_key_is_parsed_with_or_without_the_prefix() {
        let bare = "01".repeat(32);
        let prefixed = format!("0x{bare}");
        assert_eq!(parse_secret(&bare).unwrap(), [1u8; 32]);
        assert_eq!(parse_secret(&prefixed).unwrap(), [1u8; 32]);
        // Whitespace from a paste is the common case, not an exotic one.
        assert_eq!(parse_secret(&format!("  {prefixed}\n")).unwrap(), [1u8; 32]);
    }

    /// The refusal names the SHAPE and never the value. This is the test that
    /// keeps a private key out of a bug report.
    #[test]
    fn a_bad_key_never_appears_in_its_own_error() {
        let secret = "d3adbeef".repeat(9); // 72 chars — wrong length
        let e = parse_secret(&secret).expect_err("must refuse");
        assert!(!e.contains("d3adbeef"), "the error echoed the key: {e}");
        assert!(e.contains("72"), "say the shape: {e}");

        let not_hex = "z".repeat(64);
        let e = parse_secret(&not_hex).expect_err("must refuse");
        assert!(!e.contains("zzz"), "the error echoed the input: {e}");
    }

    /// One function decides whether the update notice fires, so its edges
    /// live here: only a MEASURED newer version speaks, and every other
    /// state — current, ahead, unpublished, unreadable — stays silent
    /// rather than nagging or, worse, reassuring.
    #[test]
    fn only_a_measured_newer_client_raises_the_notice() {
        let card = serde_json::json!({"client": {"version": "0.2.0"}});
        assert_eq!(newer_client(Some(&card), "0.1.0"), Some("0.2.0".into()));
        assert_eq!(newer_client(Some(&card), "0.2.0"), None, "current is quiet");
        assert_eq!(newer_client(Some(&card), "0.3.0"), None,
                   "a dev build ahead of the shelf is not asked to downgrade");
        assert_eq!(newer_client(Some(&serde_json::json!({})), "0.1.0"), None,
                   "an origin that publishes no client says nothing");
        assert_eq!(newer_client(None, "0.1.0"), None,
                   "could not look is not an update, and not up-to-date either");
    }

    // ── the pairing's refusal order, with no network and no keystore ────────

    /// Panics if consulted: for refusals that must happen before the origin.
    struct NoHttp;
    impl SigninHttp for NoHttp {
        fn challenge(&self, _: &str, _: &str) -> scry_net::Fetched<serde_json::Value> {
            panic!("the origin was consulted before the local refusal")
        }
        fn deliver(&self, _: &str, _: &str, _: &serde_json::Value)
            -> scry_net::Fetched<serde_json::Value> {
            panic!("a proof was delivered with nothing signed")
        }
    }

    /// A challenge that answers 404, for the expired-code path.
    struct Gone;
    impl SigninHttp for Gone {
        fn challenge(&self, _: &str, _: &str) -> scry_net::Fetched<serde_json::Value> {
            scry_net::Fetched::status(404)
        }
        fn deliver(&self, _: &str, _: &str, _: &serde_json::Value)
            -> scry_net::Fetched<serde_json::Value> {
            panic!("delivered after a refused challenge")
        }
    }

    fn no_signer() -> Shared {
        Arc::new(Mutex::new(scry_vault::LocalSigner::at("/nonexistent/keystore.json")))
    }

    #[test]
    fn a_bad_code_is_refused_before_a_dialog_or_the_origin() {
        let asked = Rc::new(RefCell::new(0u32));
        let a2 = Rc::clone(&asked);
        let ask: Ask = Rc::new(move |_| {
            *a2.borrow_mut() += 1;
            None
        });
        let e = pair_browser(&no_signer(), "https://x.example", "nope", &ask, &NoHttp)
            .unwrap_err();
        assert!(e.contains("not a sign-in code"), "{e}");
        assert_eq!(*asked.borrow(), 0, "no dialog may open before the shape check");
    }

    #[test]
    fn no_account_refuses_before_a_dialog_or_the_origin() {
        let ask: Ask = Rc::new(|_| panic!("asked for a passphrase with no account"));
        let e = pair_browser(&no_signer(), "https://x.example", "ABCD-2345", &ask, &NoHttp)
            .unwrap_err();
        assert!(e.contains("No account"), "{e}");
    }

    /// An expired code costs one request and NO passphrase — the dialog only
    /// ever opens over a code the origin says is waiting.
    #[test]
    fn an_expired_code_is_refused_before_the_passphrase() {
        // A keystore FILE is enough: `at` reads only the public address, and
        // this path never unlocks. No slow scrypt in this test on purpose.
        let path = std::env::temp_dir().join(format!(
            "scry-signin-test-{}.json",
            std::process::id()
        ));
        std::fs::write(
            &path,
            r#"{"address": "24445efddb08d4938e3e3627042b2cf4063d9092"}"#,
        )
        .expect("write test keystore");
        let signer: Shared =
            Arc::new(Mutex::new(scry_vault::LocalSigner::at(&path)));
        let ask: Ask = Rc::new(|_| panic!("asked for a passphrase over a dead code"));
        let e = pair_browser(&signer, "https://x.example", "abcd-2345", &ask, &Gone)
            .unwrap_err();
        let _ = std::fs::remove_file(&path);
        assert!(e.contains("not waiting to sign in"), "{e}");
        // The lowercased, dashed input was normalised into the refusal's code.
        assert!(e.contains("ABCD2345"), "{e}");
    }

    #[test]
    fn a_cancelled_prompt_is_not_an_empty_answer() {
        let ask = scripted_ask(vec![None]);
        assert_eq!(ask("anything"), None, "cancel must stay cancel");
    }

    #[test]
    fn mismatched_passphrases_are_refused_and_say_so() {
        let log = Rc::new(RefCell::new(Vec::new()));
        let ask = scripted_ask(vec![Some("one".into()), Some("two".into())]);
        let got = ask_twice(&ask, &recording_tell(Rc::clone(&log)), "p");
        assert!(got.is_none(), "a mismatch must not yield a passphrase");
        assert_eq!(log.borrow()[0].0, Told::Refused);
        assert!(log.borrow()[0].1.contains("nothing was written"));
    }
}
